clean-build:
	rm -rf *.png
	rm -rf temp/
	rm -rf screenshots/
	rm -rf error/
	rm -rf log/
	rm -rf har/
	rm -rf geckodriver.log
	mkdir temp
	mkdir screenshots
	mkdir error
	mkdir log
	mkdir har

run:
	python attack.py
