clean-build:
	rm --force --recursive *.png
	rm --force --recursive temp/
	rm --force --recursive screenshots/
	rm --force --recursive error/
	rm --force --recursive log/
	rm -rf geckodriver.log
	mkdir temp/
	mkdir screenshots/
	mkdir error/
	mkdir log

run:
	python attack.py
