clean-build:
	rm -rf *.png
	rm -rf temp/
	rm -rf screenshots/
	rm -rf error/
	rm -rf log/
	rm -rf har/
	rm -rf netflix_titles
	rm -rf geckodriver.log
	mkdir temp
	mkdir screenshots
	mkdir error
	mkdir log
	mkdir har
	mkdir netflix_titles

run:
	python attack.py
