// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "f2a963ae-cb75-4c1f-8e3d-6e8e76cef580");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1561573075);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 20);
user_pref("browser.eme.ui.firstContentShown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1561573045);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 80);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c15a030f-c6ae-4fc0-a587-b878af2b5ea2}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1561808868995");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1561810695995");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1561808869733");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1561812469733");
user_pref("browser.search.region", "CH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190620092152");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1561808866");
user_pref("browser.slowStartup.averageTime", 676);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190620092152");
user_pref("browser.startup.homepage_override.mstone", "67.0.4");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1561573046989");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "67.0.4");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "d0081530795c468aaab9eb31981c6362");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190620092152");
user_pref("extensions.lastAppVersion", "67.0.4");
user_pref("extensions.lastPlatformVersion", "67.0.4");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"cf61768a-debe-42b6-b1df-f57d1d6bec52\",\"fxmonitor@mozilla.org\":\"8eb232b8-92c4-4023-a5c0-80b622a061d2\",\"screenshots@mozilla.org\":\"84af849f-862a-47af-b7b3-7b3238fc2db4\",\"webcompat-reporter@mozilla.org\":\"0f650bb2-558a-4add-aade-cd7c0a0154bd\",\"webcompat@mozilla.org\":\"d3d59303-1863-4b76-b176-70db8c7ad554\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.eme.enabled", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1561573082);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190620092152");
user_pref("media.gmp-manager.lastCheck", 1561573082);
user_pref("media.gmp-widevinecdm.abi", "x86_64-gcc3");
user_pref("media.gmp-widevinecdm.lastUpdate", 1561573083);
user_pref("media.gmp-widevinecdm.version", "4.10.1196.0");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "94c24d4a-8c17-435f-bebf-1f7ea148fd20");
user_pref("security.sandbox.plugin.tempDirSuffix", "6367ee6d-1b2a-4493-a32a-47a702c7e3e5");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1561808866);
user_pref("toolkit.telemetry.cachedClientID", "9e3ab6ad-5118-48ec-abca-b8e903f67ccf");
user_pref("toolkit.telemetry.previousBuildID", "20190620092152");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("trailhead.firstrun.interruptsExperiment", "control");
